INSERT INTO java_quiz(quiz_no, question, a, b, c, d, answer) VALUES 
(1, 'What is the default value of a boolean variable in Java?', 'true', 'false', 'null', '0', 'b'),
(2, 'Which of the following is not a valid data type in Java?', 'int', 'float', 'char', 'doubleint', 'd'),
(3, 'What does the ''final'' keyword do in Java?', 'Makes a variable constant', 'Indicates an abstract method', 'Defines a class that cannot be inherited', 'All of the above', 'd'),
(4, 'Which of the following is used to declare a constant in Java?', 'constant', 'final', 'static', 'const', 'b'),
(5, 'Which of the following statements is true about constructors in Java?', 'A constructor can return a value', 'A constructor must have the same name as the class', 'A constructor cannot be overloaded', 'A constructor cannot have parameters', 'b'),
(6, 'Which of the following is not a valid loop structure in Java?', 'for', 'while', 'repeat', 'do-while', 'c'),
(7, 'What will be the output of the following code? \nSystem.out.println(10 + 20 + ''A'');', '30A', '30', '80', '110', 'c'),
(8, 'Which of the following is a valid method signature in Java?', 'public void myMethod()', 'public myMethod()', 'void myMethod()', 'public void myMethod[]', 'a'),
(9, 'Which keyword is used to import a package in Java?', 'import', 'include', 'using', 'require', 'a'),
(10, 'Which method is used to get the length of an array in Java?', 'array.length()', 'array.length', 'array.getLength()', 'array.size()', 'b'),
(11, 'Which of the following is not a valid access modifier in Java?', 'public', 'private', 'protected', 'static', 'd'),
(12, 'Which collection type in Java stores unique elements?', 'List', 'Set', 'Queue', 'Map', 'b'),
(13, 'What is the default value of an integer variable in Java?', '0', 'null', 'undefined', '0.0', 'a'),
(14, 'What is the size of an ''int'' in Java?', '16 bits', '32 bits', '64 bits', '128 bits', 'b'),
(15, 'Which of the following is used to define an interface in Java?', 'class', 'interface', 'abstract', 'implements', 'b'),
(16, 'Which method is used to start a thread in Java?', 'start()', 'run()', 'execute()', 'begin()', 'a'),
(17, 'Which of the following is the superclass of all Java classes?', 'Object', 'Class', 'Thread', 'String', 'a'),
(18, 'Which of the following is not a valid exception handling keyword in Java?', 'try', 'catch', 'finally', 'except', 'd'),
(19, 'Which of the following is used to terminate a loop in Java?', 'stop', 'exit', 'break', 'continue', 'c'),
(20, 'What is the result of the expression ''5 + 3 * 2'' in Java?', '16', '11', '13', '10', 'b');
